### ISSUE TITLE
Some TODOs

### ISSUE THREAD

**Issue by philbucher** [philbucher/KratosSalomePlugin#15]
- [x] ModelPart => #19
    - [x] Use py-PointerVectorSet from CoSim pyKratos again => #19
    - [x] Implement Properties => #19
    - [x] Implement ModelPart-Data => #19
    - [x] Implement Entity Data for Nodes & Geom-Entities => #19
- [x] Try to use rel-imports ~(and maybe get rid of some `__init__.py`s~ => #41 
- [x] Finish MeshGroup with Testing => #16
    - [x] add also 0D and BallElements => #16
- [ ] GenericApp should be able to write multiple ModelParts
- [x] ~refactor WriteMpda with staticmethods~
- [x] ~improve names in MeshInterface~ => will not be done bcs the Geometries are called Entities in Salome, this way is more consistent
- [ ] tests for the cantilever example
- [x] make cantilever example readme nicer
- [x] salome-utils: Add `IsMesh` and rename others to `...Proxy`
- [x] after adding colored logs also support [NO_COLOR](https://no-color.org/) right away => #55
- [x] make log-prints left centered => #55
- [x] improve versioning: https://semver.org/ => #57
- [ ] functionalities to convert GiD project to Salome (e.g. most important the `*.geo` file that contains the geometry (project needs to be saved as Ascii))
- [x] also reload the `__init__.py`s when reloading the modules since they can also contain code that is otherwise not reloaded => #65
- [x] for consistency it probably makes sense to rename the folder (once more) from `ks_plugin` to `kratos_salome_plugin` => #58
- [ ] use f-strings instead of `format` => postponed since is Python 3.6!
- [ ] use [PEP 257 -- Docstring Conventions](https://www.python.org/dev/peps/pep-0257/) for documentation

**Comment by philbucher** [comment]
closing for now, the remaining things will be addressed in future releases
